#################
# n8n PLAYBOOK #
#################
---
- hosts: "all"
  become: true 
  roles:
    - docker
  #  - nginx
  #  - mysql
  #  - php 
  tasks:
  - name: Ping сервер
    ansible.builtin.ping:    
      
