---
# Востановление из backup с Google Drive
- name: Остановить Docker-контейнеры перед восстановлением
  community.docker.docker_compose_v2:
    project_src: /opt/containers
    state: absent
  ignore_errors: yes

- name: Очистить старые данные вольюмов
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/containers/data/nginx
    - /opt/containers/data/letsencrypt
    - /opt/containers/data/n8n
    - /opt/containers/docker-compose.yml

- name: Скачать указанный бекап с Google Drive
  shell: "rclone copy 'gdrive_backup:AnsibleBackups/{{ inventory_hostname }}/{{ backup_file_name }}' /tmp/"
  args:
    executable: /bin/bash

- name: Распаковать архив с данными
  unarchive:
    src: "/tmp/{{ backup_file_name }}"
    dest: /opt/containers/data/
    remote_src: yes
    extra_opts: [--strip-components=1] # Может потребоваться для удаления корневой папки из архива

- name: Запустить Docker-контейнеры
  community.docker.docker_compose_v2:
    project_src: /opt/containers
    state: present
    restarted: yes