---
# Востановление из backup с Google Drive
- name: Остановить Docker-контейнеры перед восстановлением
  community.docker.docker_compose_v2:
    project_src: /opt/containers
    state: absent
  ignore_errors: yes

- name: Очистить старые данные вольюмов
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/containers/data/nginx
    - /opt/containers/data/letsencrypt
    - /opt/containers/data/n8n

- name: Скачать указанный бекап с Google Drive
  shell: "rclone copy 'gdrive03:backup_test/srv_test/{{ backup_file_name }}' /tmp/"
  args:
    executable: /bin/bash

- name: Распаковать архив с данными
  unarchive:
    src: "/tmp/{{ backup_file_name }}"
    dest: /opt/containers/
    remote_src: yes
    #extra_opts: [--strip-components=1] # Может потребоваться для удаления корневой папки из архива

  # Востанавливаем права для пользователя 
- name: Установить права для каталога n8n
  file:
    path: /opt/containers/data/n8n
    state: directory
    recurse: yes
    owner: 1000
    group: 1000

- name: Запустить Docker-контейнеры
  community.docker.docker_compose_v2:
    project_src: /opt/containers
    state: present