# inventory/prod/group_vars/traefik_config.yml
---
# Общие настройки доменов
main_domain: "winzardy.com" #"post-ai.tw1.su"#"winzardy.com" # Ваш основной домен

# Настройки Traefik
traefik_ssl_email: "services.n8n@winzardy.com"
traefik_api_insecure: true # В production отключаем insecure API
traefik_enable_dashboard_access: true # Если вы хотите доступ к дашборду
traefik_dashboard_port: 8085 # Порт для дашборда Traefik
traefik_dashboard_port_in: 8080