---
- name: Остановить и удалить контейнеры через docker-compose
  shell: docker-compose down -v
  args:
    chdir: /opt/containers
  ignore_errors: true

- name: Удалить директорию с docker-compose файлами и данными
  file:
    path: /opt/containers
    state: absent

- name: Удалить образы n8n и nginx-proxy-manager
  docker_image:
    name: "{{ item }}"
    state: absent
  loop:
    - n8nio/n8n
    - jc21/nginx-proxy-manager
  ignore_errors: true