---
# Файл задач для роли prometheus
- name: Установить Docker SDK для Python
  ansible.builtin.pip:
    name: docker
    state: present
  become: yes

- name: Создать директорию для конфигурации Prometheus
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Скопировать файл конфигурации Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: '0644'
  become: yes
  notify: Перезапустить контейнер Prometheus

- name: Развернуть контейнер Prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image_name }}:{{ prometheus_image_tag }}"
    restart_policy: "{{ prometheus_restart_policy }}"
    ports:
      - "{{ prometheus_host_port }}:9090"
    volumes:
      - "{{ prometheus_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "{{ prometheus_data_dir }}:/prometheus" # Директория для данных Prometheus
  become: yes
  notify: Перезапустить контейнер Prometheus

- name: Убедиться, что контейнер Prometheus запущен
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    state: started
  become: yes