services:
  - name: n8n
    domain: n8n.example.com
    port: 5678
  - name: wordpress
    domain: wp.example.com
    port: 80
  - name: outline
    domain: outline.example.com
    port: 8443
    
traefik_docker_network_name: "traefik_proxy_network"
traefik_email_name: "services.n8n@winzardy.com"