---
# Файл обработчиков для роли prometheus
- name: Перезапустить контейнер Prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    state: started
    restart: true
  become: yes