---
- name: Setup Docker and Deploy Grafana
  hosts: grafana_vps # Замените на вашу группу хостов из inventory.ini
  become: yes # Большинство задач требуют sudo

  vars:
    # Здесь можно переопределить значения по умолчанию из роли grafana, если нужно
    # Например, для установки более безопасного пароля:
    #grafana_admin_password: "YourSuperSecurePassword123!" # !!! ЗАМЕНИТЕ ЭТОТ ПАРОЛЬ !!!
    # grafana_plugins: "grafana-worldmap-panel" # Пример переопределения плагинов

  roles:
    - role: docker_compose  # Имя вашей роли для установки Docker
    - role: grafana # Имя вашей роли для развертывания Grafana
    - role: prometheus

  # Можно добавить post_tasks, если нужно выполнить что-то после обеих ролей
  # post_tasks:
  #   - name: Print Grafana URL
  #     ansible.builtin.debug:
  #       msg: "Grafana should be accessible at http://{{ ansible_default_ipv4.address | default(ansible_host) }}:{{ grafana_host_port }} (User: {{ grafana_admin_user }})"