#################
# n8n PLAYBOOK #
#################
---
- hosts: "n8n_vps"
  become: yes 
  roles:
    - docker_compose
    - apps
  tasks:
  - name: Ping сервер
    ansible.builtin.ping:    
      
